import type { Choice } from '../types';

// Every choice has at least one clear downside. Prereqs gate the "advanced"
// tier so early runs feel constrained and late runs feel powerful.
export const CHOICES: Choice[] = [
  {
    id: 'breather',
    name: 'Catch Your Breath',
    desc: "No big ship today. Burn down the ticket queue, fix some flakes, breathe.",
    icon: 'wrench',
    cost: 0,
    tier: 0,
    immediate: { reputation: 1, securityPosture: 2, techDebt: -3 },
    upside: ['$0 cost', '-3 tech debt', '+2 security · +1 reputation'],
    downside: ['No new capability. If attacks land you have nothing extra to lean on.'],
  },
  {
    id: 'loadtest-scale',
    name: 'Loadtest & Scale',
    desc: 'Spin up another app server after a load test reveals the bottleneck.',
    icon: 'scale',
    cost: 180,
    tier: 0,
    immediate: { addServer: 'app', capacity: 60 },
    ongoing: { capacityMul: 1.05, upkeep: 8, duration: 9999 },
    upside: ['+1 app server', '+5% fleet capacity'],
    downside: ['$180 + $8/day upkeep', 'More surface area if unpatched'],
  },
  {
    id: 'inbound-monitoring',
    name: 'Inbound Monitoring',
    desc: 'Deploy NetFlow + IDS at the edge to reveal attack signatures early.',
    icon: 'radar',
    cost: 120,
    tier: 0,
    immediate: { securityPosture: 8 },
    ongoing: { monitoringBonus: 0.25, logSpeed: 1.2, duration: 9999 },
    upside: ['Threats surface 25% faster', 'Log stream sharpens'],
    downside: ['$120 upfront', 'Adds noise to the log until tuned'],
  },
  {
    id: 'harden-firewall',
    name: 'Harden Firewall',
    desc: 'Tighten edge ACLs and drop low-rep ASNs aggressively.',
    icon: 'shield',
    cost: 90,
    tier: 0,
    immediate: { securityPosture: 6 },
    ongoing: { firewallBlockPct: 0.35, falsePositivePct: 0.08, duration: 9999 },
    upside: ['Drops 35% of attack traffic at the edge'],
    downside: ['Blocks 8% of legit users', 'Worse during viral surges'],
  },
  {
    id: 'deploy-waf',
    name: 'Deploy WAF',
    desc: 'Layer a Web Application Firewall in front of the app tier.',
    icon: 'shield',
    cost: 200,
    tier: 1,
    prereqs: { choices: ['inbound-monitoring'] },
    immediate: { securityPosture: 12 },
    ongoing: { wafBlockPct: 0.55, falsePositivePct: 0.04, upkeep: 6, duration: 9999 },
    upside: ['Neutralises most L7 attacks (SQLi, cred-stuff)'],
    downside: ['$200 + $6/day', 'Needs monitoring to tune', 'Small latency hit'],
  },
  {
    id: 'rate-limit',
    name: 'Rate Limiting',
    desc: 'Per-IP and per-route token buckets at the edge.',
    icon: 'gauge',
    cost: 80,
    tier: 0,
    ongoing: { rateLimitPct: 0.25, falsePositivePct: 0.05, duration: 9999 },
    upside: ['Flattens volumetric spikes by 25%'],
    downside: ['Angers power users (reputation drag during surges)'],
  },
  {
    id: 'patch',
    name: 'Patch Servers',
    desc: 'Rolling restart after a kernel + dependency sweep.',
    icon: 'chip',
    cost: 60,
    tier: 0,
    immediate: { patchAll: true, securityPosture: 10, reputation: -2 },
    upside: ['Closes zero-day exposure', 'All servers marked patched'],
    downside: ['Brief rolling-restart: -2 reputation tick'],
  },
  {
    id: 'hire-sre',
    name: 'Hire an SRE',
    desc: 'Another pair of hands means faster incident response.',
    icon: 'user',
    cost: 260,
    tier: 1,
    prereqs: { minDay: 3 },
    ongoing: { incidentSpeed: 1.4, upkeep: 14, duration: 9999 },
    upside: ['Threats resolve 40% faster', 'Team morale +'],
    downside: ['$260 sign-on + $14/day salary'],
  },
  {
    id: 'tech-debt',
    name: 'Pay Down Tech Debt',
    desc: 'Refactor the gnarly auth module. Nobody will thank you.',
    icon: 'wrench',
    cost: 100,
    tier: 0,
    immediate: { techDebt: -25, securityPosture: 4 },
    upside: ['-25 tech debt', 'Future choices cost less'],
    downside: ['$100 spent now for silent returns'],
  },
  {
    id: 'cache',
    name: 'Cache Layer',
    desc: 'Drop Redis in front of the DB tier for hot paths.',
    icon: 'cloud',
    cost: 140,
    tier: 0,
    immediate: { addServer: 'cache' },
    ongoing: { cacheHitPct: 0.4, capacityMul: 1.25, upkeep: 5, duration: 9999 },
    upside: ['+25% effective capacity', 'DB tier breathes easier'],
    downside: ['Hides real load from loadtests', 'Stale-data risk on events'],
  },
  {
    id: 'siem',
    name: 'Enable SIEM Logging',
    desc: 'Centralised log pipeline with correlation rules.',
    icon: 'scroll',
    cost: 150,
    tier: 1,
    prereqs: { choices: ['inbound-monitoring'] },
    immediate: { securityPosture: 8 },
    ongoing: { logSpeed: 1.6, incidentSpeed: 1.15, upkeep: 4, duration: 9999 },
    upside: ['Incidents resolve 15% faster', 'Log velocity way up'],
    downside: ['$150 + $4/day storage', 'Alert fatigue if untuned'],
  },
  {
    id: 'incident-drill',
    name: 'Incident Drill',
    desc: 'Tabletop exercise. Test the runbooks.',
    icon: 'flame',
    cost: 70,
    tier: 0,
    immediate: { securityPosture: 6, reputation: 3 },
    ongoing: { incidentSpeed: 1.15, duration: 9999 },
    upside: ['Team responds 15% faster', 'Morale bump'],
    downside: ['A day of lost feature work'],
  },
  {
    id: 'pentest',
    name: 'Contract a Pentest',
    desc: 'External team probes the stack. Findings are ugly but actionable.',
    icon: 'bug',
    cost: 220,
    tier: 1,
    prereqs: { minDay: 4 },
    immediate: { securityPosture: 18, revealHidden: true, techDebt: 8 },
    upside: ['+18 security posture', 'Reveals hidden threats this run'],
    downside: ['$220', '+8 tech debt (a backlog of tickets)'],
  },
  {
    id: 'backup',
    name: 'Backup Strategy',
    desc: 'Encrypted, tested, off-site. The one you keep meaning to set up.',
    icon: 'archive',
    cost: 110,
    tier: 0,
    immediate: { securityPosture: 6 },
    ongoing: { upkeep: 3, duration: 9999 },
    upside: ['Ransomware loses most of its teeth'],
    downside: ['$110 + $3/day', 'Only matters if you get hit'],
  },
  {
    id: 'db-replica',
    name: 'DB Replica',
    desc: 'Hot standby + read replica.',
    icon: 'database',
    cost: 200,
    tier: 1,
    prereqs: { minDay: 3 },
    immediate: { addServer: 'data' },
    ongoing: { capacityMul: 1.12, upkeep: 7, duration: 9999 },
    upside: ['Read capacity up, HA on the data tier'],
    downside: ['$200 + $7/day', 'More surface area'],
  },
  {
    id: 'cdn',
    name: 'CDN Rollout',
    desc: 'Push static assets to an edge network.',
    icon: 'globe',
    cost: 160,
    tier: 1,
    prereqs: { minDay: 2 },
    immediate: { securityPosture: 4 },
    ongoing: { inboundMul: 0.8, capacityMul: 1.15, upkeep: 5, duration: 9999 },
    upside: ['Origin sees 20% less traffic'],
    downside: ['$160 + $5/day', 'Cache purge bugs on viral surges'],
  },
  {
    id: 'zero-trust',
    name: 'Zero-Trust Migration',
    desc: 'mTLS everywhere. No implicit network trust.',
    icon: 'lock',
    cost: 320,
    tier: 2,
    prereqs: { choices: ['siem', 'patch'], minDay: 6 },
    immediate: { securityPosture: 25, techDebt: -10 },
    ongoing: { falsePositivePct: -0.03, upkeep: 10, duration: 9999 },
    upside: ['Huge security posture boost', 'Insider threats neutralised'],
    downside: ['$320 + $10/day', 'Week of migration pain'],
  },
];

export const CHOICES_BY_ID = new Map(CHOICES.map((c) => [c.id, c]));
